### ISSUE TITLE
Feature request: Config indentation or autodetect current indentation

### ISSUE THREAD

**Issue by BadWolf42** [Mips2648/plugins-translations#13]
Hello Mips,

Thanks for this github-action, it saves a lot of time and is very simple to deploy :)

I just tested on [plugin-brother](https://github.com/BadWolf42/plugin-brother), with [this workflow](https://github.com/BadWolf42/plugin-brother/blob/e7f07801c7a7a8c2a94cfac6fcb22faa59d4c527/.github/workflows/translations.yml) and got [this result](https://github.com/BadWolf42/plugin-brother/commit/d91bff9be102e2d8b325bacf64aeb273cca8ee77).

As you can see, `core/i18n/en_EN.json` has been generated using spaces to indent json and `plugin_info/info.json` using tabs.
I use the same indentation in both files (4 spaces) but I understand that it is not the same for everyone.
I know that it is statically set in `src/translate_plugin.py` [line 165](https://github.com/Mips2648/plugins-translations/blob/cfa48910c3d7d9935901d55d3cbfb02ef8ba0da1/src/translate_plugin.py#L165) and [line 322](https://github.com/Mips2648/plugins-translations/blob/cfa48910c3d7d9935901d55d3cbfb02ef8ba0da1/src/translate_plugin.py#L322).

Could it be possible to have a config option to set the indentation char or number for each file type (info/translations)?
Or maybe auto-detect the current indentation of each file type and use the same?

Thanks again,
Bad

**Comment by Mips2648** [comment]
Hi,

Thanks again for the feedback.

Do you have an actual need for this (except the fact that maybe you prefer/found it better/nice).
Because I cannot think of any pros or cons to have 2 spaces or 4 spaces or tab or whatever, it is even more true given the fact that these are files that we will never ever open again (hopefully).
So no, I prefer not to add an option that doesn't bring any value, even if it wouldn't be difficult to implement.

I know that with the first workflow run, it could be that there is lot of changes due to spaces but this can be ignored while doing the comparaison:
![image](https://github.com/user-attachments/assets/cdf4279f-48b2-4096-b1a9-ec4c59c13d62)

I had to choose one format. I could have roll a dice but I did choose 4 spaces because that's what Jeedom is using in their translations files, because there is no other valid criteria.

**Comment by BadWolf42** [comment]
Hi Mips, thanks for the reply.

I don't have any "actual need" for this, except that I prefer/find it better/nicer :)
I understand you point of view, there is no need to complexify the configuration.

I will close this issue, thanks again for your time
